"use strict";
module.exports = {
  // 1xx - Informational
  CONTINUE: "Request received, please continue",
  SWITCHING_PROTOCOLS: "Switching to new protocol",
  PROCESSING: "Processing request",
  EARLY_HINTS: "Early hints before final response",

  // 2xx - Success
  OK: "Request succeeded",
  CREATED: "Resource successfully created",
  ACCEPTED: "Request accepted for processing",
  NON_AUTHORITATIVE_INFORMATION:
    "Returned metadata is from a local or third-party copy",
  NO_CONTENT: "Request succeeded, no content returned",
  RESET_CONTENT: "Reset document view",
  PARTIAL_CONTENT: "Partial content returned",
  MULTI_STATUS: "Multiple status codes returned",
  ALREADY_REPORTED: "Resource already reported",
  IM_USED: "Instance manipulation applied",

  // 3xx - Redirection
  MULTIPLE_CHOICES: "Multiple options available",
  MOVED_PERMANENTLY: "Resource moved permanently",
  FOUND: "Resource found at different URI",
  SEE_OTHER: "See another resource for response",
  NOT_MODIFIED: "Resource not modified",
  TEMPORARY_REDIRECT: "Temporary redirect",
  PERMANENT_REDIRECT: "Permanent redirect",

  // 4xx - Client Error
  BAD_REQUEST: "Bad request",
  UNAUTHORIZED: "Authentication required",
  PAYMENT_REQUIRED: "Payment required",
  FORBIDDEN: "Access forbidden",
  NOT_FOUND: "Resource not found",
  METHOD_NOT_ALLOWED: "HTTP method not allowed",
  NOT_ACCEPTABLE: "Response unacceptable based on headers",
  PROXY_AUTHENTICATION_REQUIRED: "Proxy authentication required",
  REQUEST_TIMEOUT: "Request timeout",
  CONFLICT: "Conflict error",
  GONE: "Resource permanently gone",
  LENGTH_REQUIRED: "Content length required",
  PRECONDITION_FAILED: "Precondition failed",
  PAYLOAD_TOO_LARGE: "Payload too large",
  URI_TOO_LONG: "URI too long",
  UNSUPPORTED_MEDIA_TYPE: "Unsupported media type",
  RANGE_NOT_SATISFIABLE: "Requested range not satisfiable",
  EXPECTATION_FAILED: "Expectation failed",
  IM_A_TEAPOT: "Server refuses to brew coffee in a teapot",
  MISDIRECTED_REQUEST: "Request sent to wrong server",
  UNPROCESSABLE_CONTENT: "Unable to process the contained instructions",
  LOCKED: "Resource is locked",
  FAILED_DEPENDENCY: "Request failed due to dependency",
  TOO_EARLY: "Request is too early",
  UPGRADE_REQUIRED: "Upgrade protocol required",
  PRECONDITION_REQUIRED: "Precondition header required",
  TOO_MANY_REQUESTS: "Too many requests",
  REQUEST_HEADER_FIELDS_TOO_LARGE: "Header fields too large",
  UNAVAILABLE_FOR_LEGAL_REASONS: "Unavailable due to legal reasons",

  // 5xx - Server Error
  INTERNAL_SERVER_ERROR: "Internal server error",
  NOT_IMPLEMENTED: "Not implemented",
  BAD_GATEWAY: "Bad gateway",
  SERVICE_UNAVAILABLE: "Service unavailable",
  GATEWAY_TIMEOUT: "Gateway timeout",
  HTTP_VERSION_NOT_SUPPORTED: "HTTP version not supported",
  VARIANT_ALSO_NEGOTIATES: "Negotiation resulted in circular reference",
  INSUFFICIENT_STORAGE: "Insufficient storage",
  LOOP_DETECTED: "Infinite loop detected",
  NOT_EXTENDED: "Additional extensions required",
  NETWORK_AUTHENTICATION_REQUIRED: "Network authentication required",
};
